class AppImages {
  static const String error = 'assets/global_icon/failure.svg';
  static const String help = 'assets/global_icon/help.svg';
  static const String success = 'assets/global_icon/success.svg';
  static const String warning = 'assets/global_icon/warning.svg';
  static const String errorIcon = 'assets/global_icon/errorIcon.svg';
  static const String refreshIcon = 'assets/global_icon/refreshIcon.svg';
  static const String emptyFolderIcon =
      'assets/global_icon/emptyFolderIcon.svg';
  static const String offlineIcon = 'assets/global_icon/offlineIcon.svg';
  static const String galleryIcon = 'assets/global_icon/gallery.svg';
  static const String cameraIcon = 'assets/global_icon/camera.svg';
  static const String eyeHideIcon = 'assets/global_icon/eyeHideIcon.svg';
  static const String eyeShowIcon = 'assets/global_icon/eyeShowIcon.svg';
  static const String pickImgIcon = 'assets/svg/pickImgIcon.svg';
  static const String closeIcon = 'assets/svg/closeIcon.svg';
  static const String logoIcon = 'assets/images/play_store.png';
  static const String profileEmptyImage = 'assets/images/profileEmptyImage.png';
  static const String onboarding1 = 'assets/icons/onboarding1.png';
  static const String supportIcon = 'assets/svg/support_icon.svg';
  static const String langIcon = 'assets/svg/langIcon.svg';
  static const String noDataImage = 'assets/images/noDataImage.png';
  static const String exceptionImage = 'assets/images/exceptionImage.png';
  static const String addAddressImage = 'assets/images/addAddressImage.png';
  static const String addressLocationIcon =
      'assets/svg/addressLocationIcon.svg';
  static const String locationMapIcon = 'assets/icons/location_map_icon.png';
  static const String refreshCw = 'assets/images/refresh-cw-03.png';
  static const String trendDown = 'assets/images/trend_down.png';
  static const String phone = 'assets/images/phone.png';
  static const String support = 'assets/images/support.png';
  static const String send = 'assets/images/send.png';
  static const String orderIcon = 'assets/icons/orders_icon.png';
  static const String hawiaDetailesIcon = 'assets/svg/hawiaDetailesIcon.svg';
  static const String locationIcon = 'assets/svg/locationIcon.svg';
  static const String containerIcon = 'assets/svg/renameIcon.svg';
  static const String timeIcon = 'assets/svg/timeIcon.svg';
  static const String arrowDownIcon = 'assets/svg/arrowDownIcon.svg';
  static const String truckImage = 'assets/images/truckImage.png';
  static const String facebookIcon = 'assets/images/facebook.png';
  static const String instagram = 'assets/images/instagram.png';
  static const String linkedin = 'assets/images/linkedin.png';
  static const String twitter = 'assets/images/twitter.png';
  static const String whatsapp = 'assets/images/whatsapp.png';
  static const String loginImage = 'assets/images/loginImage.png';
  static const String bellIcon = 'assets/svg/bellIcon.svg';
  static const String sendIcon = 'assets/svg/sendIcon.svg';
  static const String hawiaDriver = 'assets/images/hawiaDriver.png';
}
